stages:
  - test
  - publish

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

# Make quality report downloadable
code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]
  rules:
    - if: '$CI_COMMIT_TAG == null'

sast:
  variables:
    SAST_EXCLUDED_PATHS: test/**

# Lint js files.
lint-js:
 image: node
 stage: test
 tags:
   - docker
 script:
   - npm install -g eslint
   - eslint --ignore-pattern "**/*.min.js" $CI_PROJECT_DIR

# Performs unit testing.
unit-test:
  coverage: '/Statements\s*:\s*(\d+(?:\.\d+)?\%)/'
  image: node:16-alpine
  stage: test
  artifacts:
    paths: [coverage]
  tags:
    - docker
  script:
    - npm i -g mocha nyc
    - npm ci .
    - npm run coverage

# Publish package to NPM.
publish:
  stage: publish
  image: node
  tags:
    - docker
  only:
    - tags
    - triggers
  script:
    - npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
    - npm publish

build:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  tags:
    - docker
  only:
    - tags
    - triggers
  script:
    - TAG=${CI_COMMIT_TAG:1}
    # - MAJ=$(echo "$TAG" | cut -d. -f1)
    - MIN=$(echo "$TAG" | cut -d. -f1,2)
    - docker build --pull 
      -t "gcsboss/$CI_PROJECT_NAME:$MIN" 
      -t "gcsboss/$CI_PROJECT_NAME:$TAG"
      -t "gcsboss/$CI_PROJECT_NAME" 
      .
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - docker push "gcsboss/$CI_PROJECT_NAME:$MIN"
    - docker push "gcsboss/$CI_PROJECT_NAME:$TAG"
    - docker push "gcsboss/$CI_PROJECT_NAME"
